# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: sjohnsonaz
    - task: Docker@2
      displayName: Build and Push Client
      inputs:
        command: buildAndPush
        repository: docker-example_client
        buildContext: '$(Build.SourcesDirectory)/client'
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Build and Push Server
      inputs:
        command: buildAndPush
        repository: docker-example_server
        buildContext: '$(Build.SourcesDirectory)/server'
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)