version: '3.8'
services:
  server:
    build:
      target: dev
    ports:
      - '9229:9229'
    volumes: 
      - ./server:/server
      - server_node_modules:/server/node_modules
  client:
    build:
      target: dev
    ports:
      - '8081:8081'
    volumes: 
      - ./client:/app/client
      - client_node_modules:/app/client/node_modules
volumes:
  server_node_modules:
  client_node_modules: