version: '3.8'
services:
  ingress:
    build:
      context: ./ingress
      dockerfile: Dockerfile.dev
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '9229:9229'
    volumes: 
      - ./server:/server
      - server_node_modules:/server/node_modules
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - ./client:/client
      - client_node_modules:/client/node_modules
volumes:
  server_node_modules:
  client_node_modules: