version: '3.6'
services:
  server:
    build:
      context: ./server
    command: ["npm", "run", "debug"]
    container_name: server
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - '8080:8080'
    volumes: 
      - ./client/src:/src
      - node_modules:/src/node_modules
volumes:
  node_modules: