version: '3.6'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - '9229:9229'
    volumes: 
      - ./server/src:/src
      - ./server/dist:/dist
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - '8080:8080'
    volumes: 
      - ./client/src:/src
      - node_modules:/src/node_modules
volumes:
  node_modules: