version: '3.6'
services:
  server:
    build:
      context: ./server
    command: ["npm", "run", "debug"]
    container_name: server
    ports:
      - '8080:8080'
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - '80:80'
