apiVersion: v1
kind: Service
metadata:
  name: client
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: client
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client 
  replicas: 1
  template:
    metadata:
      labels:
        app: client 
    spec:
      containers:
      - name: client 
        image: sjohnsonaz.azurecr.io/docker-example/client
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80