apiVersion: v1
kind: Service
metadata:
    name: ingress
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
    selector:
        app: docker-example-ingress
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: docker-example-ingress 
spec:
  selector:
    matchLabels:
      app: docker-example-ingress 
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-example-ingress 
    spec:
      containers:
        - name: docker-example-ingress 
          image: docker-example_ingress
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: docker-example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: docker-example-client
          servicePort: 8081
      - path: /api
        backend:
          serviceName: docker-example-server
          servicePort: 8081
