apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: docker-example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: docker-example-client
          servicePort: 8081
      - path: /api
        backend:
          serviceName: docker-example-server
          servicePort: 8081
