apiVersion: v1
kind: Service
metadata:
    name: docker-example-client
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
    selector:
        app: docker-example-client