apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: sjohnson@sjohnsonaz.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-staging
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret-stg
  namespace: default
spec:
  secretName: tls-secret-stg
  dnsNames:
    - docker-example.cascade.rocks
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - docker-example.cascade.rocks
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer