apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-prod
spec:
  secretName: certificate-prod
  dnsNames:
    - docker-example.cascade.rocks
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer